baseURL = "https://laserradesca.github.io/agrihugo"
defaultContentLanguage = 'it'

[languages]
  [languages.it]
    title = "Cascina La Cà | La Serradesca Società Agricola"
    languageName = "Italiano"
    weight = 1
    [languages.it.menu]
      [[languages.it.menu.main]]
      name = "Chi siamo"
      url = "about/"
      weight = 1
      [[languages.it.menu.main]]
      name = "La nostra offerta"
      url = "services/"
      weight = 2
      [[languages.it.menu.main]]
      name = "Contattaci"
      url = "contact/"
      weight = 3
    [languages.it.params]
      [languages.it.params.address]
        address = "località Casotto 1 <br> Torre de' Roveri (BG)"
        email = "info@laserradesca.com"
        openingHours = "Chiamaci o seguici sui social per sapere le aperture stagionali"
        phone = "342 6385086"
      [languages.it.params.flag]
        flag = "images/flags/it.jpg"

  [languages.en]
    title = "Cascina La Cà | La Serradesca Società Agricola"
    languageName = "English"
    weight = 2
    [lanugages.en.menu]
      [[languages.en.menu.main]]
      name = "About"
      url = "about/"
      weight = 1
      [[languages.en.menu.main]]
      name = "Our offer"
      url = "services/"
      weight = 2
      [[languages.en.menu.main]]
      name = "Contact us"
      url = "contact/"
      weight = 3
    [languages.en.params]
      [languages.en.params.address]
        address = "località Casotto 1 <br> Torre de' Roveri (BG), Italy"
        email = "info@laserradesca.com"
        openingDesc = "Opening hours from 1st June 2023:"
        toBook = "For info, or to set up a visit by appointment:"
        openingHours = "<ul><li>Tuesdays 4pm - 8pm<li>Thursdays 4pm - 8pm<li>Saturdays 4pm - 8pm</ul>"
        phone = "+39 342 6385086"
      [languages.en.params.flag]
        flag = "images/flags/au.jpg"

[params]
  logo = "images/logos/logo-leaf.png"
  formspreeURL = "https://formspree.io/f/meqndazp"
