baseURL = "https://www.laserradesca.com"
defaultContentLanguage = 'it'
canonifyurls = true

[languages]
  [languages.it]
    title = "Cascina La Cà | La Serradesca Società Agricola"
    languageName = "Italiano"
    weight = 1
    [languages.it.menu]
      [[languages.it.menu.main]]
      name = "Chi siamo"
      url = "about/"
      weight = 1
      [[languages.it.menu.main]]
      name = "Cosa troverete"
      url = "services/"
      weight = 2
      [[languages.it.menu.main]]
      name = "Contattaci"
      url = "contact/"
      weight = 3
    [languages.it.params]
      [languages.it.params.address]
        openingDesc = "Dal 4 giugno saremo aperti per la raccolta in campo ([ogni martedì, giovedì e sabato dalle ore 16 alle ore 20](https://forms.gle/e3XvciiXo4bdbCKK9)). Vi aspettiamo nei campi, anche con agri-aperitivi e assaggi nostrani!"
        openingHours = "<ul>Per iscriverti ad un laboratorio o evento, clicca ([qui](https://https://www.laserradesca.com/services/farm/))i</ul>"
        toBook = "Per informazioni o appuntamenti:"
        facebookicon = "images/social/facebook_white.png"
        facebookurl = "https://www.facebook.com/laserradesca/"
        instagramicon = "images/social/instagram_white.png"
        instagramurl = "https://www.instagram.com/laserradesca/"
        newsletter = "https://laserradesca.voxmail.it/user/register"
        email = "info@laserradesca.com"
        phone = "342 6385086"
        address = "Località Casotto 1 <br> Torre de' Roveri (BG), Italy"
      [languages.it.params.flag]
        flag = "images/flags/it.jpg"

  [languages.en]
    title = "Cascina La Cà | La Serradesca Società Agricola"
    languageName = "English"
    weight = 2
    [lanugages.en.menu]
      [[languages.en.menu.main]]
      name = "About"
      url = "about/"
      weight = 1
      [[languages.en.menu.main]]
      name = "What you'll find"
      url = "services/"
      weight = 2
      [[languages.en.menu.main]]
      name = "Contact us"
      url = "contact/"
      weight = 3
    [languages.en.params]
      [languages.en.params.address]
        openingDesc = "From 4th June, we will be open for fruit picking every ([Tuesday, Thursday and Saturday from 4pm to 8pm](https://forms.gle/e3XvciiXo4bdbCKK9)) Pass by to sample our fruit, wines and other tasty treats!"
        openingHours = "<ul>To sign up for an event or workshop, click ([here](https://https://www.laserradesca.com/services/farm/)).</ul>"
        toBook = "For info, or to set up a visit by appointment:"
        facebookicon = "images/social/facebook_white.png"
        facebookurl = "https://www.facebook.com/laserradesca/"
        instagramicon = "images/social/instagram_white.png"
        instagramurl = "https://www.instagram.com/laserradesca/"
        newsletter = "https://laserradesca.voxmail.it/user/register"
        email = "info@laserradesca.com"
        phone = "+39 342 6385086"
        address = "Località Casotto 1 <br> Torre de' Roveri (BG), Italy"
      [languages.en.params.flag]
        flag = "images/flags/au.jpg"

[params]
  logo = "images/logos/logo_leaf_icon_white_bg.png"
  formspreeURL = "https://formspree.io/f/xoqzrobq"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

    ignoreErrors = ["error-remote-getjson"]
